name: Deploy to Server

on:
  push:
    branches:
      - main  # ou la branche que vous souhaitez surveiller

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /public_html/newelles
          git pull origin main
          # Ajouter d'autres commandes pour recharger le serveur, installer des dépendances, etc
